# Generated by Django 5.2.17 on 2026-09-17 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('error', 'Ошибка'), ('warning', 'Предупреждение')], max_length=16)),
                ('field', models.CharField(blank=True, max_length=128)),
                ('row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('precinct_code', models.CharField(blank=True, max_length=64)),
                ('territory_code', models.CharField(blank=True, max_length=64)),
                ('code', models.CharField(max_length=64)),
                ('message', models.TextField()),
                ('details', models.JSONField(default=dict)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='datasets.dataset')),
            ],
            options={
                'verbose_name': 'замечание качества',
                'verbose_name_plural': 'замечания качества',
                'indexes': [models.Index(fields=['dataset', 'level'], name='validation__dataset_4ebaa2_idx'), models.Index(fields=['dataset', 'field'], name='validation__dataset_1c85b9_idx')],
            },
        ),
    ]
