# Generated by Django 5.2.17 on 2026-09-17 12:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('queued', 'В очереди'), ('running', 'Выполняется'), ('succeeded', 'Успешно'), ('failed', 'Ошибка'), ('cancelled', 'Отменён')], default='draft', max_length=20)),
                ('config_json', models.JSONField(default=dict)),
                ('seed', models.IntegerField(default=42)),
                ('library_versions', models.JSONField(default=dict)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('progress_message', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=64)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('n_used', models.PositiveIntegerField(default=0)),
                ('n_excluded', models.PositiveIntegerField(default=0)),
                ('warnings_json', models.JSONField(default=list)),
                ('outlier_ids', models.JSONField(default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='datasets.dataset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='projects.project')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'запуск анализа',
                'verbose_name_plural': 'запуски анализа',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('formula', models.CharField(blank=True, max_length=255)),
                ('included', models.BooleanField(default=True)),
                ('drop_reason', models.TextField(blank=True)),
                ('details', models.JSONField(default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='analytics.analysisrun')),
            ],
            options={
                'verbose_name': 'признак',
                'verbose_name_plural': 'признаки',
            },
        ),
        migrations.CreateModel(
            name='ModelCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.JSONField(default=list)),
                ('k', models.PositiveSmallIntegerField()),
                ('scaler', models.CharField(max_length=16)),
                ('silhouette', models.FloatField(blank=True, null=True)),
                ('calinski_harabasz', models.FloatField(blank=True, null=True)),
                ('davies_bouldin', models.FloatField(blank=True, null=True)),
                ('min_cluster_share', models.FloatField(blank=True, null=True)),
                ('internal_score', models.FloatField(blank=True, null=True)),
                ('ari_mean', models.FloatField(blank=True, null=True)),
                ('ari_percentile', models.FloatField(blank=True, null=True)),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('rejected', models.BooleanField(default=False)),
                ('reject_reason', models.TextField(blank=True)),
                ('n_used', models.IntegerField(default=0)),
                ('n_excluded', models.IntegerField(default=0)),
                ('complexity', models.IntegerField(default=0)),
                ('boxplot', models.JSONField(default=dict)),
                ('silhouette_samples', models.JSONField(default=list)),
                ('tik_distribution', models.JSONField(default=dict)),
                ('labels', models.JSONField(default=list)),
                ('precinct_ids', models.JSONField(default=list)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='analytics.analysisrun')),
            ],
            options={
                'verbose_name': 'кандидат модели',
                'verbose_name_plural': 'кандидаты моделей',
                'ordering': ['-total_score', '-internal_score'],
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('chart', 'График'), ('export_csv', 'CSV'), ('export_xlsx', 'XLSX'), ('export_json', 'JSON'), ('report_html', 'HTML-отчёт'), ('report_pdf', 'PDF-отчёт')], max_length=32)),
                ('file', models.FileField(upload_to='artifacts/%Y/%m/')),
                ('meta_json', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='analytics.analysisrun')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='analytics.modelcandidate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='recommended_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_for', to='analytics.modelcandidate'),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='selected_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_for', to='analytics.modelcandidate'),
        ),
        migrations.CreateModel(
            name='ClusterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.IntegerField()),
                ('size', models.IntegerField()),
                ('share', models.FloatField()),
                ('centers', models.JSONField(default=dict)),
                ('stats', models.JSONField(default=dict)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='analytics.modelcandidate')),
            ],
            options={
                'unique_together': {('candidate', 'cluster_id')},
            },
        ),
        migrations.CreateModel(
            name='ClusterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.IntegerField()),
                ('distance_to_center', models.FloatField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='datasets.precinctrecord')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='analytics.modelcandidate')),
            ],
            options={
                'indexes': [models.Index(fields=['candidate', 'cluster_id'], name='analytics_c_candida_4c4de2_idx')],
                'unique_together': {('candidate', 'record')},
            },
        ),
    ]
